module tb_array_os();
    parameter int N = 4;                                // Size of NxN array. Should match rtl/accelerator/systolic_array.sv and scripts/generate_accelerator_tests.py
    parameter int DATA_W = 8;                           // Width of A and W 
    parameter int NUM_TESTS = 1005;                     // Total number of tests generated by scripts/generate_accelerator_test.py
    localparam int SUM_W = 2*DATA_W + $clog2(N);        // Width of accumulated sum 

    logic                   clk, reset, start;
    logic [DATA_W-1:0]      a_in [N];
    logic [DATA_W-1:0]      w_in [N];

    /* verilator lint_off UNUSEDSIGNAL */
    logic [DATA_W-1:0]      a_out [N];
    logic [DATA_W-1:0]      w_out [N];
    /* verilator lint_on UNUSEDSIGNAL */

    logic [SUM_W-1:0]       sum_out [N][N]; 


    integer             cycle;
    integer             total_cycles;
    integer             errors;
    integer             test;

    // Golden-model storage
    logic [DATA_W-1:0]         A_mat        [NUM_TESTS][N][N];
    logic [DATA_W-1:0]         W_mat        [NUM_TESTS][N][N];
    logic [SUM_W-1:0]          C_expected   [NUM_TESTS][N][N];

    array_os #(.N(N), .DATA_W(DATA_W), .SUM_W(SUM_W)) dut (
        .clk(clk), .reset(reset), .start(start),
        .a_in(a_in), .w_in(w_in),
        .a_out(a_out), .w_out(w_out),
        .sum_out(sum_out)
    );

    // Clock
    always begin
        clk = 1; #5; clk = 0; #5;
    end

    // Reset + init
    initial begin
        $readmemh("sim/A.tv", A_mat);
        $readmemh("sim/W.tv", W_mat);
        $readmemh("sim/C.tv", C_expected);

        $dumpfile("sim/array_os_waves.vcd");
        $dumpvars(0, tb_array_os);

        cycle = 0; errors = 0; test = 0;
        reset = 1; start = 0; total_cycles = 0;
        #22; reset = 0;
    end

    // Driver
    always @(posedge clk) begin
        if (~reset) begin
            start <= 0; 
            for (int i = 0; i < N; i++) begin
            a_in[i] <= '0;
            w_in[i] <= '0;
        end
            if (cycle < N) begin
                if (cycle == 0) begin 
                    start <= 1;
                end
                for (int r = 0; r < N; r++) begin
                    a_in[r] <= A_mat[test][r][cycle];
                end
                for (int c = 0; c < N; c++) begin
                    w_in[c] <= W_mat[test][cycle][c];
                end
            end
            total_cycles <= total_cycles + 1;
            if (cycle == 3*N - 1) begin
                test <= test + 1;
                cycle <= 0;
            end
            else begin
                cycle <= cycle + 1;
            end
        end
    end

    // Scoreboard
    always @(negedge clk) begin
        if (~reset) begin
            if (cycle == 3*N - 1) begin
                for (int r = 0; r < N; r++) begin
                    for (int c = 0; c < N; c++) begin
                        if (sum_out[r][c] !== C_expected[test][r][c]) begin
                            $display("Error at Test %0d, Cycle %0d: Row %0d, Col %0d", test, cycle, r, c);
                            $display("  Expected: %h", C_expected[test][r][c]);
                            $display("  Got:      %h", sum_out[r][c]);
                            errors <= errors + 1;
                        end
                    end
                end
                if (cycle == 3*N - 1) begin
                    if(test == NUM_TESTS - 1) begin
                        $display("%0d Total cycles completed. %0d Cycles-per-matrix", total_cycles + 1, (total_cycles + 1)/NUM_TESTS);
                        if (errors == 0)
                            $display("SUCCESS: All tests completed perfectly!");
                        else
                            $display("FAILURE: completed with %0d errors.", errors);
                        $finish;
                    end
                end
            end
        end
    end

endmodule
